apiVersion: v1
kind: Service
metadata:
    name: "vaccination-site"
    namespace: default
    labels:
        app: "vaccination-site"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "vaccination-site"
